### ISSUE TITLE
Version with resistors for arduino

### ISSUE THREAD

**Issue by mistepien** [svenpetersen1965/Joystick-for_commodore_and_atar#1]
Hello,

great project. Could you be so nice and add version with resistors for arduino?

220 Ohm | 1 | Up
220 Ohm | 2 | Down
220 Ohm | 3 | Left
220 Ohm | 4 | Right
220 Ohm | 5 | Pot Y
220 Ohm | 6 | Fire
(n/c) | - | 7 | +5V
GND | - | 8 | GND
 220 Ohm | 9 | Pot X

It would be very nice to have ability to make C64 joystick running with arduino board. Such board would great interface between arduino and C64.

**Comment by svenpetersen1965** [comment]
In which way should the resistors be added? To ground, to VCC or series? I need this a bit more detailed to consider it.

**Comment by mistepien** [comment]
![Joystick_Simple_Interconnect_v0_with_resistors](https://user-images.githubusercontent.com/9516457/148562339-b0ffb446-d350-45ed-8569-14d276fb3827.png)

I thought about sth like that. Above the goldpins J2 next row of goldpins. Each pin in new upper row would be separated by place for resistor. Except 5V and GND. Arduino would be connectec through the upper row. If someone does not need arduno the lower goldpin row will be good for him and he will not solder resistors. 

In addition please connect POTX, POTY and 5V to J4 respective soldering spots.

BTW, great idea. Just solder all cables from db9 cable and utilize it in civilized way. So simple and genius as well. Thanks!

**Comment by svenpetersen1965** [comment]
Potx/y are not connnected anways. Why does the Arduino require the 220Ω in series? Do you know that? Is it a protection, in case the pin direction is accidentally set to output?

**Comment by mistepien** [comment]
https://giters.com/doj/Ultimate-USB-to-Controlport

the is a passage about resistors between arduino and control port.

**Comment by mistepien** [comment]
and why POTX and POTY are disconnected?

**Comment by svenpetersen1965** [comment]
Because the joystick only has 4 direction bits and fire. No analog outputs.

**Comment by svenpetersen1965** [comment]
And I had a look at your link. The project is about connecting a USB joystick to an arduino, which then mimics a vintage joystick at the control port. And you want to use my board as a carrier for the resistors. Well, a perf board will do that job as well. So please forgive me, when I close this issue and don’t change my board. 
Regards,
Sven
